# Author: Tom Sapletta · Part of the ifURI solution — GENERATED by urirun-reasoner.
"""urirun-connector-calendar — Headless calendar over ICS/CalDAV: list events, create (gated), parse .ics. No GUI.

Generated autonomously to satisfy a capability the reasoner found blocked (no connector
served the calendar:// scheme). Built to URI_NATIVE_CONNECTOR_CHECKLIST: lazy imports,
handlers never raise (urirun envelope), queries in-process.
"""
from __future__ import annotations

from typing import Any

import urirun

CONNECTOR_ID = "calendar"
conn = urirun.connector(CONNECTOR_ID, scheme="calendar")


def _ok(**kw: Any) -> dict[str, Any]:
    return urirun.ok(connector=CONNECTOR_ID, **kw)


def _fail(msg: str, action: str, **extra: Any) -> dict[str, Any]:
    return urirun.fail(msg, connector=CONNECTOR_ID, action=action, **extra)


def _vevents_from_ics_text(text: str) -> list[dict[str, Any]]:
    """Parse a VCALENDAR string into event dicts. Prefer icalendar, fall back to stdlib."""
    events: list[dict[str, Any]] = []
    try:
        import icalendar  # type: ignore
        cal = icalendar.Calendar.from_ical(text)
        for comp in cal.walk('VEVENT'):
            def _g(key: str) -> str:
                v = comp.get(key)
                if v is None:
                    return ''
                try:
                    return v.to_ical().decode() if hasattr(v, 'to_ical') else str(v)
                except Exception:  # noqa: BLE001
                    return str(v)
            events.append({
                'uid': _g('UID'),
                'summary': _g('SUMMARY'),
                'dtstart': _g('DTSTART'),
                'dtend': _g('DTEND'),
                'description': _g('DESCRIPTION'),
            })
        return events
    except ImportError:
        pass
    # stdlib fallback: crude line-based VEVENT block parse
    cur: dict[str, Any] | None = None
    key_map = {'UID': 'uid', 'SUMMARY': 'summary', 'DTSTART': 'dtstart',
               'DTEND': 'dtend', 'DESCRIPTION': 'description'}
    for raw in text.splitlines():
        line = raw.rstrip('\r')
        if line.strip() == 'BEGIN:VEVENT':
            cur = {'uid': '', 'summary': '', 'dtstart': '', 'dtend': '', 'description': ''}
        elif line.strip() == 'END:VEVENT':
            if cur is not None:
                events.append(cur)
            cur = None
        elif cur is not None and ':' in line:
            name, _, value = line.partition(':')
            name = name.split(';', 1)[0].strip().upper()
            if name in key_map:
                cur[key_map[name]] = value.strip()
    return events


@conn.handler("events/query/list", isolated=False,
              meta={"label": "List calendar events from an .ics file or CalDAV URL — read-only"})
def events_query_list(ics_path: str = '', caldav_url: str = '', user: str = '',
                      password: str = '', start: str = '', end: str = '') -> dict[str, Any]:
    """List events from a local .ics file OR a CalDAV URL. Read-only, no mutation."""
    try:
        if ics_path:
            with open(ics_path, 'r', encoding='utf-8') as fh:
                text = fh.read()
            events = _vevents_from_ics_text(text)
            if start or end:
                events = [e for e in events
                          if (not start or e.get('dtstart', '') >= start)
                          and (not end or e.get('dtstart', '') <= end)]
            return _ok(action='calendar-list', source='ics', count=len(events), events=events)
        if caldav_url:
            import caldav  # type: ignore
            client = caldav.DAVClient(url=caldav_url, username=user or None, password=password or None)
            principal = client.principal()
            events: list[dict[str, Any]] = []
            for cal in principal.calendars():
                try:
                    if start or end:
                        found = cal.date_search(start=start or None, end=end or None)
                    else:
                        found = cal.events()
                except Exception:  # noqa: BLE001
                    found = cal.events()
                for ev in found:
                    events.extend(_vevents_from_ics_text(ev.data))
            return _ok(action='calendar-list', source='caldav', count=len(events), events=events)
        return _fail('ics_path or caldav_url required', 'calendar-list')
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "calendar-list")


@conn.handler("event/command/create", isolated=True,
              meta={"gated": True, "label": "Append an event (VEVENT) to an .ics file — GATED, reversible/append"})
def event_command_create(ics_path: str = '', summary: str = '', start: str = '',
                         end: str = '', description: str = '') -> dict[str, Any]:
    """Append a VEVENT to an .ics file. Reversible (append-only). GATED: the executor
    requires an approval:// gate before it runs (it mutates a file)."""
    try:
        import os
        import uuid
        from datetime import datetime, timezone
        if not ics_path:
            return _fail('ics_path required', 'calendar-create')
        if not summary:
            return _fail('summary required', 'calendar-create')
        uid = f"{uuid.uuid4()}@urirun-calendar"
        dtstamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')

        def _esc(s: str) -> str:
            return s.replace('\\', '\\\\').replace(';', '\\;').replace(',', '\\,').replace('\n', '\\n')

        vevent_lines = [
            'BEGIN:VEVENT',
            f'UID:{uid}',
            f'DTSTAMP:{dtstamp}',
            f'SUMMARY:{_esc(summary)}',
        ]
        if start:
            vevent_lines.append(f'DTSTART:{start}')
        if end:
            vevent_lines.append(f'DTEND:{end}')
        if description:
            vevent_lines.append(f'DESCRIPTION:{_esc(description)}')
        vevent_lines.append('END:VEVENT')
        vevent = '\r\n'.join(vevent_lines) + '\r\n'

        exists = os.path.exists(ics_path) and os.path.getsize(ics_path) > 0
        if exists:
            with open(ics_path, 'r', encoding='utf-8') as fh:
                text = fh.read()
            idx = text.rfind('END:VCALENDAR')
            if idx != -1:
                new_text = text[:idx] + vevent + text[idx:]
            else:
                new_text = text.rstrip('\r\n') + '\r\n' + vevent
            with open(ics_path, 'w', encoding='utf-8') as fh:
                fh.write(new_text)
        else:
            cal = ('BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//urirun//calendar//EN\r\n'
                   + vevent + 'END:VCALENDAR\r\n')
            with open(ics_path, 'w', encoding='utf-8') as fh:
                fh.write(cal)
        return _ok(action='calendar-create', uid=uid, ics_path=ics_path, summary=summary)
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "calendar-create")


@conn.handler("ics/query/parse", isolated=False,
              meta={"label": "Parse an .ics string or file into structured events — pure, no network"})
def ics_query_parse(ics_text: str = '', ics_path: str = '') -> dict[str, Any]:
    """Parse a VCALENDAR string (or file) into structured events. Pure, no network."""
    try:
        text = ics_text
        if not text and ics_path:
            with open(ics_path, 'r', encoding='utf-8') as fh:
                text = fh.read()
        if not text:
            return _fail('ics_text or ics_path required', 'calendar-parse')
        events = _vevents_from_ics_text(text)
        return _ok(action='calendar-parse', count=len(events), events=events)
    except Exception as exc:  # noqa: BLE001
        return _fail(str(exc), "calendar-parse")


def urirun_bindings() -> dict[str, Any]:
    return conn.bindings()


def connector_manifest() -> dict[str, Any]:
    return urirun.load_manifest(__package__) or {"id": CONNECTOR_ID}


def main(argv: list[str] | None = None) -> int:
    return conn.cli(argv, manifest_prose=urirun.load_manifest(__package__))


if __name__ == "__main__":
    raise SystemExit(main())
